language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
 # tag version needs to be updated when dependnecy updated in gradle.build
 - git clone --branch 0.1 "https://github.com/rafalmag/xmas-gifts-drawer.git" xmas
 - cd xmas
 - chmod +x gradlew
 - ./gradlew install
 - cd ..
 - chmod +x gradlew
 
after_success:
 - ./gradlew jacocoTestReport coveralls
